### ISSUE TITLE
Enhancement, maybe add an option to edit the colors/name of a created theme the user has made.

### ISSUE THREAD

**Issue by recoveryawareness** [d-exclaimation/CardJitsuClone#5]

**Comment by d-exclaimation** [comment]
Sounds like a good idea, but I haven't touch the codebase in like 3 years. Feel free to make PR about it though, any contributions is always welcome. Alternatively, you are also free to clone the repo and use it as a starting point to make your own version.

**Comment by recoveryawareness** [comment]
> Sounds like a good idea, but I haven't touch the codebase in like 3 years. Feel free to make PR about it though, any contributions is always welcome. Alternatively, you are also free to clone the repo and use it as a starting point to make your own version.

thank you, I might just do that and code it myself :) then submit a pull request 😊
